name: Kubernetes CI/CD

on:
  push:
    branches: [ main ]

env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/flask-k8s-app

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip install -r requirements.txt
          pytest

  build-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build & push
        run: |
          docker build -t $IMAGE:${{ github.sha }} .
          docker push $IMAGE:${{ github.sha }}

  deploy:
    needs: build-push
    # CHANGED: This runs on your computer to access Minikube
    runs-on: [self-hosted]  
    steps:
      - uses: actions/checkout@v4
      
      # We skip 'azure/setup-kubectl' because your laptop already has kubectl
      # We skip 'Configure kubeconfig' because the runner uses your local ~/.kube/config
      
      - name: Deploy to Local Minikube
        run: |
          # Ensure the deployment exists locally first or use 'kubectl apply -f deployment.yaml'
          kubectl set image deployment/flask-app flask=$IMAGE:${{ github.sha }}
          kubectl rollout status deployment/flask-app

